### ISSUE TITLE
Avoid using global variables

### ISSUE THREAD

**Issue by gabrielperales** [FAC9/gitbusters_api#30]
Try to create an anonymous closure to wrap all you code. That will keep all your variables hidden from outside of that closure and you won't be populating the global scope with variables than sudden't be read outside of there.

[Here](http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html) you can read more about that pattern and about the module pattern.

**Comment by gabrielperales** [comment]
BTW if you are doing TDD you will need at least access to the functions that you want to test... so you can do that with the module pattern, where you will be exposing only one variable/object as a global variable and inside you will have your functions as attributes of your object, so you can keep accessing to those functions through the global object...  but you will only have one global variable 😃

**Comment by stevehopkinson** [comment]
Fixed in the latest commit. Still need to refactor our tests and expose functions through the module, but we'll do that soon.
