### ISSUE TITLE
Final test could fail for multiple different reasons - not the most useful test

### ISSUE THREAD

**Issue by jsms90** [FAC9/gitbusters_api#52]
Really you want to split this into each individual step, so that if your test fails, you know which piece of code is responsible.

If your test fails, it could be because:
- the button click is not linked (correctly) to any functions in your JavaScript
- your GET request has failed (for whatever reason - written incorrectly, or for reasons out of your control i.e. server side)
- a successful GET request is performed but does not update the DOM

**Comment by denesnori** [comment]
tests are updated now
